// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WebUI.Config.VideoInput {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.Panel pnlSelector;
		
		protected System.Web.UI.WebControls.DropDownList ddlInput;
		
		protected System.Web.UI.WebControls.Panel pnlEnable;
		
		protected System.Web.UI.WebControls.Button btnEnable;
		
		protected System.Web.UI.WebControls.Panel pnlConfig;
		
		protected System.Web.UI.WebControls.DropDownList ddlCodec;
		
		protected System.Web.UI.WebControls.DropDownList ddlResolution;
		
		protected System.Web.UI.WebControls.DropDownList ddlFrameRate;
		
		protected System.Web.UI.WebControls.CheckBox chkHFlip;
		
		protected System.Web.UI.WebControls.CheckBox chkVFlip;
		
		protected System.Web.UI.WebControls.Button btnSave;
		
		protected System.Web.UI.WebControls.Button btnCancel;
		
		protected System.Web.UI.WebControls.Button btnDisable;
	}
}
