INCLUDE+=-I. -I../../libclientserver/include -I../../liblogger/include
INCLUDE+=`pkg-config --cflags gstreamer-1.0` -I/usr/local/include/gstreamer-1.0

LIBS+=../../liblogger/liblogger.a ../../libclientserver/libclientserver.a
LIBS+=`pkg-config --libs gstreamer-1.0`
LIBS+=/usr/local/lib/libgstrtspserver-1.0.so.0
LIBS+=-pthread

CPP=g++
CPP_OPTS+=-Wall -ggdb -std=c++11
MKDEP=gcc -E -MM


