INCLUDE+=-I./include


#Gstreamer
INCLUDE+=$(shell pkg-config --cflags gstreamer-1.0)
INCLUDE+=-I/usr/local/include/gstreamer-1.0
LIBS+=$(shell pkg-config --libs gstreamer-1.0)
LIBS+=/usr/local/lib/libgstrtspserver-1.0.so.0

#Jsoncpp
INCLUDE+=$(shell pkg-config --cflags jsoncpp)
LIBS+=$(shell pkg-config --libs jsoncpp)

INCLUDE+=$(shell pkg-config --cflags libclientserver)
LIBS+=$(shell pkg-config --libs libclientserver)

#liblogger
INCLUDE+=$(shell pkg-config --cflags liblogger)
LIBS+=$(shell pkg-config --libs liblogger)

LIBS+=-pthread

CPP=g++
CPP_OPTS+=-Wall -ggdb -std=c++11
MKDEP=gcc -E -MM


