// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WebUI {
	
	
	public partial class Site1 {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder head;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lblUsername;
		
		protected System.Web.UI.WebControls.Label lblVersion;
		
		protected System.Web.UI.WebControls.Panel pnlLiveView;
		
		protected System.Web.UI.WebControls.Panel pnlAdmin;
		
		protected System.Web.UI.WebControls.Panel pnlConfig;
		
		protected System.Web.UI.WebControls.Panel pnlSystem;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder1;
	}
}
