// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WebUI.Config.Sys {
	
	
	public partial class Debug {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.DropDownList ddlDebugEnabled;
		
		protected System.Web.UI.WebControls.Button btnSave;
		
		protected System.Web.UI.WebControls.Button btnCancel;
	}
}
